package test:logging@1.1.1;

interface logger {
    use test:types/types@1.0.0.{level};

    log: func(lvl: level, msg: string);
}

world logging {
    export logger;

    import println: func(msg: string);
}
