name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]

permissions: read-all

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: write
    steps:
      - name: Audit all outbound runner calls
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup devenv
        uses: andyl-technologies/github-actions/setup-devenv@master

      - name: Setup Rust cache
        uses: andyl-technologies/github-actions/rust-cache@master
        with:
          cache-all-crates: true
          save-condition: true

      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@v5
        with:
          filename: 'coverage.cobertura.xml'
