name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [master]

permissions:
  actions: write
  contents: write

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ci-enterprise-large]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup devenv
        uses: andyl-technologies/andyl-github-action/setup-devenv@master

      - name: Setup Rust cache
        uses: andyl-technologies/andyl-github-action/rust-cache@master
        with:
          cache-all-crates: true
          save-condition: true

      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@v5
        with:
          filename: 'coverage.cobertura.xml'
