name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [master]

permissions:
  actions: write
  contents: write

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ci-enterprise-medium]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add Nix binaries to PATH
        run: |
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"

      - name: Run coverage
        run: nix run nixpkgs#devenv -- shell wasm-trampoline-coverage

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@v5
        with:
          filename: 'coverage.cobertura.xml'
