name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]

permissions: read-all

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup devenv
        uses: andyl-technologies/github-actions/setup-devenv@a1b683853d3459471b7661235be4b76eda58c652 # master

      - name: Setup Rust cache
        uses: andyl-technologies/github-actions/rust-cache@a1b683853d3459471b7661235be4b76eda58c652 # master
        with:
          cache-all-crates: true
          save-condition: true

      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@17b6103ac2d3b9bb6c7a8562ac22a4c010d6d52f # v5
        with:
          filename: 'coverage.cobertura.xml'
