name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]

permissions: read-all

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1

      - name: Setup devenv
        uses: andyl-technologies/github-actions/setup-devenv@a1b683853d3459471b7661235be4b76eda58c652 # master

      - name: Setup Rust cache
        uses: andyl-technologies/github-actions/rust-cache@a1b683853d3459471b7661235be4b76eda58c652 # master
        with:
          cache-all-crates: true
          save-condition: true

      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@9e2cd22e39153feba8b4477e4fefcc0b5e2727ba # v5
        with:
          filename: 'coverage.cobertura.xml'
