name: 'cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  actions: read
  contents: write

jobs:
  cron-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: true
          cache-all-crates: true
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage
      - uses: clearlyip/code-coverage-report-action@v5
        with:
         filename: 'coverage.cobertura.xml'
