name: 'Publishing'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    environment: "publishing"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup devenv
        uses: andyl-technologies/github-actions/setup-devenv@master

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_REPO_PUBLISH_TOKEN }}
