name: 'Publishing'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    environment: "publishing"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Setup devenv
        uses: andyl-technologies/github-actions/setup-devenv@a1b683853d3459471b7661235be4b76eda58c652 # master

      - name: Publish to crates.io
        uses: katyo/publish-crates@02cc2f1ad653fb25c7d1ff9eb590a8a50d06186b # v2
        with:
          registry-token: ${{ secrets.CRATES_IO_REPO_PUBLISH_TOKEN }}
