name: 'scorecard workflow'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]

permissions: read-all

jobs:
  scorecard-analysis:
    name: 'Scorecard analysis'
    if: github.event.repository.default_branch == github.ref_name
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4.6.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Upload to code-scanning"
        if: github.event.repository.default_branch == github.ref_name
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
