name: "Run Tests"

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests:
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: sccache
        uses: Mozilla-Actions/sccache-action@main
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-all-crates: true
      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv test
