name: "Run Tests"

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv test
