name: "Run Tests"

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  build-nix-cache:
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Restore nix cache
        id: restore-nix
        uses: nix-community/cache-nix-action/restore@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        if: steps.restore-nix.outputs.hit == 'false'
        run: nix profile install nixpkgs#devenv
      - name: Save
        if: steps.restore-nix.outputs.hit == 'false'
        uses: nix-community/cache-nix-action/save@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # purge: true
          # purge-primary-key: never


  tests:
    needs: build-nix-cache
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      CARGO_INCREMENTAL: "0"

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Restore Nix store
        uses: nix-community/cache-nix-action/restore@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: sccache
        uses: Mozilla-Actions/sccache-action@main
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}


      - name: Run tests
        run: devenv test

  coverage:
    needs: build-nix-cache
    strategy:
      matrix:
        os: [ ubuntu-latest-16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Restore Nix store
        uses: nix-community/cache-nix-action/restore@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run coverage
        run: devenv shell wasm-trampoline-coverage
      - name: Generate Coverage Report
        uses: clearlyip/code-coverage-report-action@v5
        id: code_coverage_report_action
        if: ${{ github.actor != 'dependabot[bot]'}}
        with:
          filename: 'coverage.cobertura.xml'
          artifact_download_workflow_names: '"Run Tests",cron'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: code-coverage-results.md
